# Generated by Django 5.1.4 on 2025-04-22 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='recipes/')),
                ('ingredients', models.TextField(help_text="Один ингредиент в строку: 'Молоко — 1 л'")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecipeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('recipes_given', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('tg_user_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserRecipeInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField()),
                ('liked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_admin.recipe')),
            ],
            options={
                'unique_together': {('tg_user_id', 'recipe')},
            },
        ),
    ]
